name: E2E tests

on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --cache ~/.npm --prefer-offline --no-audit

      - name: Launch backend
        run: |
          wget https://raw.githubusercontent.com/Terralego/GeoCRUD/master/.env.dist -O .env
          wget https://raw.githubusercontent.com/Terralego/GeoCRUD/master/docker-compose.yml
          sed -i 's,TERRA_TILES_HOSTNAMES=http://127.0.0.1:3000,TERRA_TILES_HOSTNAMES=http://front:3000,' .env
          sed -i.bak 's/^\(POSTGRES_PASSWORD=\).*/\1test/' .env
          sed -i 's,DOMAIN_NAME=127.0.0.1,DOMAIN_NAME=front,' .env
          docker-compose run --rm django ./manage.py migrate
          docker-compose up -d
          docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/e2e.json
          docker-compose run --rm django ./manage.py loaddata /app/public/data/fixtures/demo.json

