name: JS Unit tests

on:
  push:

jobs:
  jstest:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --cache ~/.npm --prefer-offline --no-audit

      - name: Run unit tests
        run: |
          npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
