name: Lint

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          nvm use
          npm ci

      - name: Run tests
        run: |
          npm run lint
