name: Lint

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install dependencies
        run: |
          npm ci

      - name: ESlint
        run: |
          npm run lint
