name: Unit tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit

      - name: Test
        continue-on-error: true
        run: |
          npm run test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
